// Auto-generated by Aptly — do not edit manually. Injects the Google Analytics snippet
// (set from the Website Manager's Configuration tab, stored as the GOOGLE_ANALYTICS_SNIPPET
// Cloudflare Pages env var) into every page's <head>. No snippet set = a plain pass-through.
class HeadInjector {
  constructor(snippet) {
    this.snippet = snippet;
  }
  element(element) {
    element.append(this.snippet, { html: true });
  }
}

export async function onRequest({ next, env }) {
  const response = await next();
  const snippet = env.GOOGLE_ANALYTICS_SNIPPET;
  if (!snippet || !response.headers.get('content-type')?.includes('text/html')) {
    return response;
  }
  return new HTMLRewriter().on('head', new HeadInjector(snippet)).transform(response);
}
